/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CTNFT__factory } from "./CTNFT__factory";
export { CTNFTReward__factory } from "./CTNFTReward__factory";
